package com.bestbuy.cartService.entity;

import com.bestbuy.cartService.dto.CartItemDTO;
import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.util.ArrayList;
import java.util.List;

@Entity
@Data
@NoArgsConstructor  // Generates a no-args constructor
public class Cart {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // Unique ID for the cart

    private Long userId; // User ID associated with the cart

    @OneToMany(mappedBy = "cart", cascade = CascadeType.ALL, orphanRemoval = true)
    private List<CartItem> items = new ArrayList<>(); // List of cart items

    // Constructor with userId, generated by Lombok
    public Cart(Long userId) {
        this.userId = userId;
    }

    // Method to add an item to the cart (simplified)
    public void addItem(CartItem item) {
        items.add(item);
        item.setCart(this);  // Set the Cart reference in the CartItem
    }

    // Method to remove an item from the cart
    public void removeItem(CartItem item) {
        items.remove(item);
        item.setCart(null);  // Set the Cart reference in the CartItem to null
    }
}



