services:
  eureka-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - shared-network
networks:
  shared-network:
    external: true

